apiVersion: v1
kind: Namespace
metadata:
  name: newnginx-v
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: newnginx-v
spec:
  selector:
    matchLabels:
      app: nginx-app
  replicas: 2
  template:
   metadata:
     labels:
       app: nginx-app
   spec:
     containers:
      - name: nginx
        image: docker.io/nginx:latest
        volumeMounts:
         - name: hpvolume
           mountPath: "/tmp/hpvolume"
           readOnly: true
        ports:
         - containerPort: 6780
           protocol: TCP
     volumes:
      - name: hpvolume
          hostpath:
            path: /home/purushothaman/test
      
      
