apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-azurefile
  namespace: svpnamespace-nginx
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: my-azurefile
  resources:
    requests:
      storage: 1Gi
