apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: svpnamespace-nginx
spec:
  selector:
    matchLabels: 
      app: nginx-app
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers: 
      - name: nginx
        image: nginx:1.14.2
        resources:
          requests:
            memory: 300Mi
            cpu: 100m
          limits:
            memory: 1Gi
            cpu: 600m     
---
apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
  namespace: svpnamespace-nginx
spec:
  type: LoadBalancer
  ports:
  - targetPort: 80
    port: 80
    protocol: TCP
  selector:
    app: nginx-app
