apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefile
  namespace: svpnamespace-nginx
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
